name: Generate Datas

on:
  schedule: # 12시간마다 실행
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: 데이터 업데이트 작업
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: haroya01
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
